import { useState, useEffect, useMemo, useRef } from 'react'
import { type Shot } from '../../api/shots'
import { type Prompt, type GroupPrompt } from '../../api/prompts'
import { getImageUrl } from '../../api/assets'
import { type EpisodeAssetItem } from '../../pages/tabs/Tab3Assembly'

interface GroupCentralWorkAreaProps {
  projectId: number
  currentGroupId: string
  groupShots: Shot[]
  groupPrompts: Prompt[]
  savedGroupPrompt?: GroupPrompt
  episodeAssets: EpisodeAssetItem[]
  selectedItems: EpisodeAssetItem[]
  onToggleItem: (item: EpisodeAssetItem) => void
  anchorDeclaration: string       // 自动生成（只读）
  editableAnchor: string          // 可编辑版本
  onEditableAnchorChange: (text: string) => void
  specialPromptContent: string
  specialPromptScope: 'group' | 'episode'
  onSpecialPromptContentChange: (text: string) => void
  onSpecialPromptScopeChange: (scope: 'group' | 'episode') => void
  onEditGroupPrompt: (prompt: string) => void
  onSaveGroupPrompt: () => void
  onResetGroupPrompt: () => void
  onConfirmGroupPrompt: () => void
  duration: number
  setDuration: (d: number) => void
  resolution: string
  setResolution: (r: string) => void
  ratio: string
  setRatio: (r: string) => void
  onGenerateVideo: () => void
  generating: boolean
  onShowPreview: () => void
}

export default function GroupCentralWorkArea({
  projectId,
  currentGroupId,
  groupShots,
  groupPrompts,
  savedGroupPrompt,
  episodeAssets,
  selectedItems,
  onToggleItem,
  anchorDeclaration,
  editableAnchor,
  onEditableAnchorChange,
  specialPromptContent,
  specialPromptScope,
  onSpecialPromptContentChange,
  onSpecialPromptScopeChange,
  onEditGroupPrompt,
  onSaveGroupPrompt,
  onResetGroupPrompt,
  onConfirmGroupPrompt,
  duration,
  setDuration,
  resolution,
  setResolution,
  ratio,
  setRatio,
  onGenerateVideo,
  generating,
  onShowPreview,
}: GroupCentralWorkAreaProps) {
  // 计算组合提示词
  const displayPrompt = useMemo(() => {
    const isAutoGenerated = !savedGroupPrompt || !savedGroupPrompt.edited
    if (!isAutoGenerated) return savedGroupPrompt?.combined_video_prompt || ''

    const sortedShots = [...groupShots].sort((a, b) => a.shot_id.localeCompare(b.shot_id))
    const parts = sortedShots.map(shot => {
      const prompt = groupPrompts.find(p => p.shot_id === shot.shot_id)
      if (!prompt) return null
      return `【镜头${shot.shot_id}】(${shot.duration}s)\n${prompt.video_prompt}`
    }).filter(Boolean)
    return parts.join('\n\n')
  }, [groupShots, groupPrompts, savedGroupPrompt])

  const isAutoGenerated = !savedGroupPrompt || !savedGroupPrompt.edited

  const isUserEditingRef = useRef(false)
  const [editingPrompt, setEditingPrompt] = useState(displayPrompt)

  useEffect(() => {
    if (!isUserEditingRef.current) {
      setEditingPrompt(displayPrompt)
    }
  }, [displayPrompt])

  useEffect(() => {
    isUserEditingRef.current = false
    setEditingPrompt(displayPrompt)
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [currentGroupId])

  const totalDuration = groupShots.reduce((sum, s) => sum + s.duration, 0)

  return (
    <div className="flex-1 flex flex-col overflow-hidden min-w-0">
      {/* 顶部工具栏：组信息 + 生成参数 + 操作按钮 */}
      <div className="flex items-center gap-2 px-2 py-1.5 border-b border-gray-800 bg-gray-900 flex-shrink-0 flex-wrap">
        {/* 组信息 */}
        <span className="font-mono text-sm">{currentGroupId}</span>
        <span className="text-xs text-gray-500">{totalDuration.toFixed(1)}s · {groupShots.length} 镜头</span>
        {isAutoGenerated && <span className="text-xs text-blue-400">[自动拼接]</span>}
        {savedGroupPrompt?.edited && <span className="text-xs text-yellow-400">[已编辑]</span>}
        {savedGroupPrompt?.confirmed && <span className="text-xs text-green-400">✓</span>}

        <div className="flex-1" />

        {/* 生成参数 */}
        <select className="text-xs border border-gray-700 rounded px-1.5 py-1 bg-gray-800">
          <option value="seedance2.0">Seedance 2.0</option>
          <option value="seedance2.0_fast">Seedance 2.0 Fast</option>
        </select>
        <div className="flex items-center gap-1">
          <span className="text-xs text-gray-500">时长</span>
          <input
            type="number"
            value={duration}
            onChange={(e) => setDuration(Number(e.target.value))}
            className="w-12 text-xs border border-gray-700 rounded px-1.5 py-1 bg-gray-800"
          />
          <span className="text-xs text-gray-500">s</span>
        </div>
        <select
          value={resolution}
          onChange={(e) => setResolution(e.target.value)}
          className="text-xs border border-gray-700 rounded px-1.5 py-1 bg-gray-800"
        >
          <option value="1080p">1080p</option>
          <option value="720p">720p</option>
          <option value="4K">4K</option>
        </select>
        <select
          value={ratio}
          onChange={(e) => setRatio(e.target.value)}
          className="text-xs border border-gray-700 rounded px-1.5 py-1 bg-gray-800"
        >
          <option value="9:16">9:16</option>
          <option value="16:9">16:9</option>
          <option value="1:1">1:1</option>
        </select>
        <button
          onClick={onGenerateVideo}
          disabled={generating}
          className="text-xs px-3 py-1 bg-blue-600 text-white rounded hover:bg-blue-500 disabled:opacity-50"
        >
          {generating ? '生成中...' : '生成视频'}
        </button>

        <div className="w-px h-4 bg-gray-700" />

        {/* 操作按钮 */}
        <button onClick={onShowPreview} className="text-xs px-2 py-1 bg-gray-700 rounded hover:bg-gray-600">预览</button>
        {savedGroupPrompt?.edited && (
          <button onClick={onResetGroupPrompt} className="text-xs px-2 py-1 bg-gray-700 rounded hover:bg-gray-600">重置</button>
        )}
        <button
          onClick={() => { onEditGroupPrompt(editingPrompt); onSaveGroupPrompt() }}
          className="text-xs px-2 py-1 bg-gray-700 rounded hover:bg-gray-600"
        >保存</button>
        <button
          onClick={() => { onEditGroupPrompt(editingPrompt); onConfirmGroupPrompt() }}
          className="text-xs px-2 py-1 bg-blue-600 rounded hover:bg-blue-500"
        >确认</button>
      </div>

      {/* 组合提示词编辑区（上半区） */}
      <div className="flex-[5] border-b border-gray-800 p-2 flex flex-col min-h-0">
        <label className="text-xs text-gray-500 mb-1 flex-shrink-0">组合视频提示词</label>
        <textarea
          className="flex-1 p-2 bg-gray-900 border border-gray-700 rounded text-sm font-mono resize-none focus:border-blue-500 focus:outline-none"
          value={editingPrompt}
          onChange={(e) => {
            isUserEditingRef.current = true
            setEditingPrompt(e.target.value)
          }}
          placeholder="【镜头01】(3.8s)..."
        />
      </div>

      {/* 锚定区（下半区）：左右分栏 */}
      <div className="flex-[5] flex min-h-0">
        {/* 左侧：锚定文字 + 已选缩略图 */}
        <div className="w-[38%] border-r border-gray-800 p-2 flex flex-col gap-2 overflow-auto">
          <div className="text-xs text-gray-500 flex-shrink-0">
            参考图锚定 ({selectedItems.length}/6)
          </div>

          {/* 行1：自动锚定声明（灰色只读） */}
          <div>
            <div className="text-xs text-gray-600 mb-1">自动生成</div>
            <div className="text-xs text-gray-500 bg-gray-800/60 rounded p-2 border border-gray-700/50 min-h-[32px] leading-relaxed">
              {anchorDeclaration || <span className="text-gray-600">点选右侧资产生成锚定声明</span>}
            </div>
          </div>

          {/* 行2：可编辑锚定声明 */}
          <div>
            <div className="text-xs text-gray-400 mb-1">可编辑版本</div>
            <textarea
              value={editableAnchor}
              onChange={(e) => onEditableAnchorChange(e.target.value)}
              className="w-full text-xs bg-gray-800 border border-gray-700 rounded p-2 resize-none h-12 focus:border-blue-500 focus:outline-none"
              placeholder="图1是角色A，图2是场景B..."
            />
          </div>

          {/* 已选缩略图（有序编号） */}
          {selectedItems.length > 0 && (
            <div className="flex gap-1.5 flex-wrap">
              {selectedItems.map((item, i) => (
                <div key={item.key} className="relative w-12 h-12 rounded border-2 border-blue-500 overflow-hidden flex-shrink-0">
                  <img
                    src={getImageUrl(projectId, item.asset.asset_type, item.asset.asset_id, item.imageIndex)}
                    className="w-full h-full object-cover"
                    alt={item.displayName}
                  />
                  <span className="absolute bottom-0 right-0 bg-blue-600 text-white text-[10px] px-0.5 rounded-tl leading-tight">
                    {i + 1}
                  </span>
                </div>
              ))}
            </div>
          )}

          {/* 特殊提示词（第2块） */}
          <div className="border-t border-gray-700 pt-2 mt-2">
            <div className="flex items-center justify-between mb-1">
              <div className="text-xs text-gray-500">特殊提示词（第2块）</div>
              <select
                value={specialPromptScope}
                onChange={(e) => onSpecialPromptScopeChange(e.target.value as 'group' | 'episode')}
                className="text-xs border border-gray-700 rounded px-1.5 py-0.5 bg-gray-800"
              >
                <option value="group">仅本组</option>
                <option value="episode">本集全部</option>
              </select>
            </div>
            <textarea
              value={specialPromptContent}
              onChange={(e) => onSpecialPromptContentChange(e.target.value)}
              className="w-full text-xs bg-gray-800 border border-gray-700 rounded p-2 resize-none h-16 focus:border-blue-500 focus:outline-none"
              placeholder="特殊效果、风格要求等..."
            />
          </div>
        </div>

        {/* 右侧：当集资产网格 */}
        <div className="flex-1 p-2 overflow-auto">
          <div className="text-xs text-gray-500 mb-2">当集资产</div>
          {episodeAssets.length === 0 ? (
            <div className="text-xs text-gray-600 text-center mt-8">暂无资产引用数据</div>
          ) : (
            <div className={`grid gap-1.5 ${episodeAssets.length <= 10 ? 'grid-cols-5' : 'grid-cols-6'}`}>
              {episodeAssets.map(item => {
                const isSelected = selectedItems.some(s => s.key === item.key)
                const selectedIndex = selectedItems.findIndex(s => s.key === item.key)
                const imgUrl = getImageUrl(projectId, item.asset.asset_type, item.asset.asset_id, item.imageIndex)

                return (
                  <button
                    key={item.key}
                    onClick={() => onToggleItem(item)}
                    disabled={!isSelected && selectedItems.length >= 6}
                    className={`aspect-square rounded border-2 overflow-hidden relative transition-all ${
                      isSelected
                        ? 'border-blue-500 ring-2 ring-blue-500/30'
                        : 'border-gray-700 hover:border-gray-500'
                    } ${!isSelected && selectedItems.length >= 6 ? 'opacity-40 cursor-not-allowed' : ''}`}
                    title={item.displayName}
                  >
                    <img src={imgUrl} className="w-full h-full object-cover" alt={item.displayName} />
                    {/* 序号标（已选） */}
                    {isSelected && (
                      <span className="absolute top-0 left-0 bg-blue-600 text-white text-[10px] px-1 leading-tight rounded-br">
                        {selectedIndex + 1}
                      </span>
                    )}
                    {/* 名称标签 */}
                    <span className="absolute bottom-0 left-0 right-0 text-[9px] text-white bg-black/60 text-center truncate px-0.5 leading-tight py-px">
                      {item.displayName}
                    </span>
                  </button>
                )
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
