import { useState } from 'react'
import { type Shot } from '../../api/shots'
import { type Prompt, type GroupPrompt } from '../../api/prompts'
import { type Asset, getImageUrl } from '../../api/assets'

interface GroupCentralWorkAreaProps {
  projectId: number
  episodeId: number
  currentGroupId: string
  groupShots: Shot[]
  groupPrompts: Prompt[]
  savedGroupPrompt?: GroupPrompt
  groupAssets: Asset[]
  onEditGroupPrompt: (prompt: string) => void
  onSaveGroupPrompt: () => void
  onResetGroupPrompt: () => void
  onConfirmGroupPrompt: () => void
  selectedReferenceImages: string[]
  onToggleReference: (assetId: string, imageUrl: string) => void
  anchorDeclaration: string
  settings: any
  duration: number
  setDuration: (d: number) => void
  resolution: string
  setResolution: (r: string) => void
  ratio: string
  setRatio: (r: string) => void
  onGenerateVideo: () => void
  generating: boolean
  onShowPreview: () => void
}

export default function GroupCentralWorkArea({
  projectId,
  episodeId,
  currentGroupId,
  groupShots,
  groupPrompts,
  savedGroupPrompt,
  groupAssets,
  onEditGroupPrompt,
  onSaveGroupPrompt,
  onResetGroupPrompt,
  onConfirmGroupPrompt,
  selectedReferenceImages,
  onToggleReference,
  anchorDeclaration,
  settings,
  duration,
  setDuration,
  resolution,
  setResolution,
  ratio,
  setRatio,
  onGenerateVideo,
  generating,
  onShowPreview
}: GroupCentralWorkAreaProps) {
  // 计算组合提示词
  const assembleCombinedPrompt = (): string => {
    const sortedShots = [...groupShots].sort((a, b) => a.shot_id.localeCompare(b.shot_id))

    const parts = sortedShots.map(shot => {
      const prompt = groupPrompts.find(p => p.shot_id === shot.shot_id)
      if (!prompt) return null

      return `【镜头${shot.shot_id}】(${shot.duration}s)\n${prompt.video_prompt}`
    }).filter(Boolean)

    return parts.join('\n\n')
  }

  // 判断是否使用自动拼接
  const isAutoGenerated = !savedGroupPrompt || !savedGroupPrompt.edited
  const displayPrompt = isAutoGenerated ? assembleCombinedPrompt() : savedGroupPrompt?.combined_video_prompt || ''

  const [editingPrompt, setEditingPrompt] = useState(displayPrompt)

  // 当 displayPrompt 变化时更新
  useState(() => {
    setEditingPrompt(displayPrompt)
  })

  const totalDuration = groupShots.reduce((sum, s) => sum + s.duration, 0)

  return (
    <div className="w-[82%] flex flex-col overflow-hidden">
      {/* 1. 顶部栏 */}
      <div className="flex items-center justify-between p-2 border-b border-gray-800 bg-gray-900">
        <div className="flex items-center gap-2">
          <span className="font-mono text-sm">{currentGroupId}</span>
          <span className="text-xs text-gray-500">
            {totalDuration.toFixed(1)}s · {groupShots.length} 镜头
          </span>
          {isAutoGenerated && <span className="text-xs text-blue-400">[自动拼接]</span>}
          {savedGroupPrompt?.edited && <span className="text-xs text-yellow-400">[已编辑]</span>}
          {savedGroupPrompt?.confirmed && <span className="text-xs text-green-400">✓</span>}
        </div>
        <div className="flex gap-2">
          <button
            onClick={onShowPreview}
            className="text-xs px-3 py-1 bg-gray-700 rounded hover:bg-gray-600"
          >
            预览
          </button>
          {savedGroupPrompt?.edited && (
            <button
              onClick={onResetGroupPrompt}
              className="text-xs px-3 py-1 bg-gray-700 rounded hover:bg-gray-600"
            >
              重置
            </button>
          )}
          <button
            onClick={() => {
              onEditGroupPrompt(editingPrompt)
              onSaveGroupPrompt()
            }}
            className="text-xs px-3 py-1 bg-gray-700 rounded hover:bg-gray-600"
          >
            保存
          </button>
          <button
            onClick={onConfirmGroupPrompt}
            className="text-xs px-3 py-1 bg-blue-600 rounded hover:bg-blue-500"
          >
            确认
          </button>
        </div>
      </div>

      {/* 2. 组合提示词编辑区 (50%) */}
      <div className="flex-[5] border-b border-gray-800 p-3">
        <label className="text-sm font-medium mb-2 block">组合视频提示词</label>
        <textarea
          className="w-full h-[calc(100%-28px)] p-2 bg-gray-900 border border-gray-700 rounded text-sm font-mono resize-none focus:border-blue-500 focus:outline-none"
          value={editingPrompt}
          onChange={(e) => setEditingPrompt(e.target.value)}
          placeholder="【镜头01】(3.8s)..."
        />
      </div>

      {/* 3. 参考图锚定区 (30%) */}
      <div className="flex-[3] border-b border-gray-800 p-3 overflow-auto">
        <label className="text-sm font-medium mb-2 block">
          参考图锚定 ({selectedReferenceImages.length}/6)
        </label>

        {/* 8列网格 */}
        <div className="grid grid-cols-8 gap-1.5 mb-3">
          {groupAssets.map(asset => {
            const imageUrl = asset.images[0] ? getImageUrl(projectId, asset.asset_type, asset.asset_id, 1) : null
            const isSelected = imageUrl && selectedReferenceImages.includes(imageUrl)

            return (
              <button
                key={asset.asset_id}
                onClick={() => imageUrl && onToggleReference(asset.asset_id, imageUrl)}
                disabled={!imageUrl}
                className={`aspect-square rounded border-2 overflow-hidden transition-all ${
                  isSelected
                    ? 'border-blue-500 ring-2 ring-blue-500/30'
                    : 'border-gray-700 hover:border-gray-500'
                } ${!imageUrl ? 'opacity-50 cursor-not-allowed' : ''}`}
                title={asset.name}
              >
                {imageUrl ? (
                  <img src={imageUrl} className="w-full h-full object-cover" alt={asset.name} />
                ) : (
                  <div className="w-full h-full bg-gray-800 flex items-center justify-center text-xs text-gray-500">
                    {asset.name.slice(0, 2)}
                  </div>
                )}
              </button>
            )
          })}
        </div>

        {/* 已选 + 锚定声明 */}
        {selectedReferenceImages.length > 0 && (
          <>
            <div className="flex items-center gap-1 mb-2 flex-wrap">
              <span className="text-xs text-gray-500">已选:</span>
              {selectedReferenceImages.map((imgUrl, i) => (
                <div key={i} className="relative w-12 h-12 rounded border-2 border-blue-500">
                  <img src={imgUrl} className="w-full h-full object-cover rounded" alt="" />
                  <span className="absolute bottom-0 right-0 bg-blue-600 text-white text-xs px-1 rounded-tl">
                    {i + 1}
                  </span>
                </div>
              ))}
            </div>
            <div className="text-xs bg-gray-800 rounded p-2 border border-gray-700">
              <span className="text-gray-500">锚定: </span>
              <span className="text-gray-300">{anchorDeclaration}</span>
            </div>
          </>
        )}
      </div>

      {/* 4. 生成参数 (20%) */}
      <div className="flex-[2] p-3">
        <label className="text-sm font-medium mb-2 block">生成参数</label>
        <div className="grid grid-cols-5 gap-2">
          <div>
            <label className="text-xs text-gray-500 block mb-1">模型</label>
            <select className="w-full text-xs border border-gray-700 rounded px-2 py-1.5 bg-gray-800">
              <option value="seedance2.0">Seedance 2.0</option>
              <option value="seedance2.0_fast">Seedance 2.0 Fast</option>
            </select>
          </div>
          <div>
            <label className="text-xs text-gray-500 block mb-1">时长(秒)</label>
            <input
              type="number"
              value={duration}
              onChange={(e) => setDuration(Number(e.target.value))}
              className="w-full text-xs border border-gray-700 rounded px-2 py-1.5 bg-gray-800"
            />
          </div>
          <div>
            <label className="text-xs text-gray-500 block mb-1">分辨率</label>
            <select
              value={resolution}
              onChange={(e) => setResolution(e.target.value)}
              className="w-full text-xs border border-gray-700 rounded px-2 py-1.5 bg-gray-800"
            >
              <option value="1080p">1080p</option>
              <option value="720p">720p</option>
              <option value="4K">4K</option>
            </select>
          </div>
          <div>
            <label className="text-xs text-gray-500 block mb-1">比例</label>
            <select
              value={ratio}
              onChange={(e) => setRatio(e.target.value)}
              className="w-full text-xs border border-gray-700 rounded px-2 py-1.5 bg-gray-800"
            >
              <option value="9:16">9:16</option>
              <option value="16:9">16:9</option>
              <option value="1:1">1:1</option>
            </select>
          </div>
          <div className="flex items-end">
            <button
              onClick={onGenerateVideo}
              disabled={generating}
              className="w-full py-1.5 text-sm bg-blue-600 text-white rounded hover:bg-blue-500 disabled:opacity-50"
            >
              {generating ? '生成中...' : '生成视频'}
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
